/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package at.eliastrummer.gui;

import at.eliastrummer.at.xml.XMLWindowManager;
import at.eliastrummer.beans.Window;
import at.eliastrummer.utils.WindowAlreadyExistingException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.xml.sax.SAXException;

/**
 *
 * @author Elias
 */
public class WindowCreatorGUI extends javax.swing.JFrame {
    private Map<String, JFrame> windows = new HashMap<>();
    private Map<String, JDialog> dialogs = new HashMap<>();
    
    public WindowCreatorGUI() {
        initComponents();
        setLocationRelativeTo(null);
        init();
    }
    
    private void init() {
        try {
            for(Window w : XMLWindowManager.getInstance().getWindows()) {
                if(w.getType().equalsIgnoreCase("window")) {
                    createWindow(w);
                }else{
                    createDialog(w);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(WindowCreatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void createWindow(Window w) {
        JFrame f = new JFrame();
                    f.setLocation(w.getxPos(), w.getyPos());
                    f.setSize(w.getWidth(), w.getHeight());
                    f.setTitle(w.getName());
                    
                    f.addWindowListener(new WindowAdapter() {
                        public void windowClosing(WindowEvent e) {
                            try {
                                windows.remove(w.getName());
                                w.setWidth(f.getSize().width);
                                w.setHeight(f.getSize().height);
                                w.setxPos(f.getLocation().x);
                                w.setyPos(f.getLocation().y);
                                XMLWindowManager.getInstance().updateWindow(w);
                                XMLWindowManager.getInstance().saveToFile();
                            } catch (Exception ex) {
                                System.out.println(ex.toString());
                            }
                        }
                    });
                    
                    f.setVisible(true);
                    windows.put(w.getName(), f);
    }
    
    private void createDialog(Window w) {
        JDialog d = new JDialog();
                    d.setLocation(w.getxPos(), w.getyPos());
                    d.setSize(w.getWidth(), w.getHeight());
                    d.setTitle(w.getName());
                    
                    d.addWindowListener(new WindowAdapter() {
                        public void windowClosing(WindowEvent e) {
                            try {
                                windows.remove(w.getName());
                                w.setWidth(d.getSize().width);
                                w.setHeight(d.getSize().height);
                                w.setxPos(d.getLocation().x);
                                w.setyPos(d.getLocation().y);
                                XMLWindowManager.getInstance().updateWindow(w);
                                XMLWindowManager.getInstance().saveToFile();
                            } catch (Exception ex) {
                                System.out.println(ex.toString());
                            }
                        }
                    });
                    
                    d.setVisible(true);
                    dialogs.put(w.getName(), d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfWidth = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfPosX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPosY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        cbType = new javax.swing.JComboBox<>();
        btCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Width");
        getContentPane().add(jLabel1);

        tfWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWidthActionPerformed(evt);
            }
        });
        getContentPane().add(tfWidth);

        jLabel2.setText("Height");
        getContentPane().add(jLabel2);
        getContentPane().add(tfHeight);

        jLabel3.setText("Position X");
        getContentPane().add(jLabel3);
        getContentPane().add(tfPosX);

        jLabel4.setText("Position Y");
        getContentPane().add(jLabel4);
        getContentPane().add(tfPosY);

        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        getContentPane().add(tfName);

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Window", "Dialog" }));
        getContentPane().add(cbType);

        btCreate.setText("Create");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btCreate);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWidthActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        int width = Integer.parseInt(tfWidth.getText());
        int height = Integer.parseInt(tfHeight.getText());
        int xpos = Integer.parseInt(tfPosX.getText());
        int ypos = Integer.parseInt(tfPosY.getText());
        String type = (String)cbType.getSelectedItem();
        Window w = new Window(tfName.getText(), type, xpos, ypos, width, height);
        
        try {
            XMLWindowManager.getInstance().initWindow(w);
        } catch(WindowAlreadyExistingException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            return;
        } catch (Exception ex) {
            Logger.getLogger(WindowCreatorGUI.class.getName()).log(Level.SEVERE, null, ex);
        } 
        if(type.equalsIgnoreCase("window")) {
            createWindow(w);
        }else{
            createDialog(w);
        }
    }//GEN-LAST:event_btCreateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Map<String, JFrame> windowsCopy = new HashMap<>(windows);
        Map<String, JDialog> dialogsCopy = new HashMap<>(dialogs);
        
        for(Map.Entry<String, JFrame> v : windowsCopy.entrySet()) {
            v.getValue().dispatchEvent(new WindowEvent(v.getValue(), WindowEvent.WINDOW_CLOSING));
        }
        
        for(Map.Entry<String, JDialog> v : dialogsCopy.entrySet()) {
            v.getValue().dispatchEvent(new WindowEvent(v.getValue(), WindowEvent.WINDOW_CLOSING));
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCreatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCreate;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfHeight;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPosX;
    private javax.swing.JTextField tfPosY;
    private javax.swing.JTextField tfWidth;
    // End of variables declaration//GEN-END:variables
}
